del "C:\Users\admin\PycharmProjects\cz2002-mystars\src\authentication\*.class"
del "C:\Users\admin\PycharmProjects\cz2002-mystars\src\constants\*.class"
del "C:\Users\admin\PycharmProjects\cz2002-mystars\src\custom_exceptions\*.class"
del "C:\Users\admin\PycharmProjects\cz2002-mystars\src\entity\*.class"
del "C:\Users\admin\PycharmProjects\cz2002-mystars\src\text_manager\*.class"
del "C:\Users\admin\PycharmProjects\cz2002-mystars\src\view\*.class"
del "C:\Users\admin\PycharmProjects\cz2002-mystars\src\registration_controller\*.class"